### PR TITLE
Refactor: documentation

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium/react-plot-docs/issues/12

### CODE REVIEW

**Comment by wadjih-bencheikh18** [comment]
@lpatiny what do you think if we add types 
where we can explain diffrent complicated types such:
- CSSFuncProps
- ShapeFuncProps
- LabelFuncProps
- also the types mentioned here https://github.com/zakodium/react-plot/issues/370

**Comment by targos** [comment]
@lpatiny @stropitek one of you wants to have a look?

**Comment by stropitek** [comment]
When documenting the props, it would be good to add an example using this / these props.

An advantage of this other than illustrating the functionality is that if and when the api has breaking changes, we will get TS errors when building the examples and we will know that the documentation needs to be reviewed.

> what do you think if we add types section (to redirect users when we use it in different parts of docs)
> we can explain complicated types such

Yes it's a good idea to put it in a separate place.

**Comment by lpatiny** [comment]
@wadjih-bencheikh18 Lot of work being done ! Please could you take care that the build is working so that I could have a preview on netlify ?

**Comment by wadjih-bencheikh18** [comment]
> @wadjih-bencheikh18 Lot of work being done ! Please could you take care that the build is working so that I could have a preview on netlify ?

fixed , sorry about that

**Pull request merged**
